
CREATE TABLE SyncCount (
  syncCount BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  objectClass CHAR(64) CHARSET ascii COLLATE ascii_bin NOT NULL,
  isCommitted BOOL NOT NULL DEFAULT 0,
  createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX(objectClass),
  INDEX(isCommitted)
) ENGINE=INNODB;

CREATE TABLE User (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
) ENGINE=INNODB;

CREATE TABLE Client (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userId INT UNSIGNED NOT NULL,
  UUID CHAR(36) UNIQUE NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
) ENGINE=INNODB;
